FROM ruby:2.3.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-common postgresql-client nodejs

RUN mkdir /code
WORKDIR /code

ADD Gemfile /code/Gemfile
ADD Gemfile.lock /code/Gemfile.lock

RUN bundle install --without development

ENV RAILS_ENV production

ADD . /code

# Precompile Rails assets
RUN rails assets:precompile