development: &default
  adapter: sqlite3
  encoding: unicode
  database: db/dev.db

test:
  <<: *default
  database: db/test.db

production:
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>